version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-ecr: circleci/aws-ecr@8.1.2
  github-ops: voodooteam/github-ops@2
  docker: circleci/docker@2

jobs:
  dependencies:
    working_directory: ~/airbyte/airbyte-integrations/connectors/source-facebook-marketing
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout


workflows:
  version: 2
  deployment:
    jobs:
      - dependencies:
          context:
            - github-voodoo-bender
            - VOODOO_INFRA_TOOLS
      - docker/hadolint:
          dockerfiles: airbyte-integrations/connectors/source-facebook-marketing/Dockerfile
          ignore-rules: "DL3059"
      - aws-ecr/build-and-push-image:
          path: airbyte-integrations/connectors/source-facebook-marketing/
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          context: VOODOO_INFRA_TOOLS
          create-repo: false
          no-output-timeout: 20m
          repo: "data-core/vgp-data-airbyte-facebook"
          tag: << pipeline.git.revision >>
          skip-when-tags-exist: true
          requires:
            - dependencies
            - docker/hadolint
          filters:
            branches:
              only:
                - voodoo_master
